{
 "title": "SRD - Network Resources (HTTP API)",
 "templating": {
  "list": [
   { "name": "instance", "query": "label_values(up, instance)" },
   {
    "name": "volume",
    "query": "label_values(windows_logical_disk_free_bytes, volume)"
   }
  ]
 },
 "panels": [
  {
   "title": "CPU usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "(100 - (avg by (instance) (irate(windows_cpu_time_total{mode=\"idle\"}[5m])) * 100))",
     "legendFormat": "CPU %"
    }
   ]
  },
  {
   "title": "RAM usage",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "((1 - (windows_memory_available_bytes / windows_memory_physical_total_bytes)) * 100)"
    }
   ]
  },
  {
   "title": "RAM free",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "((windows_memory_available_bytes / windows_memory_physical_total_bytes) * 100)"
    }
   ]
  },
  {
   "title": "Disk Space Used and Available",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "sum by (instance, volume) (windows_logical_disk_size_bytes) / 1024 / 1024 / 1024 / 1024",
     "legendFormat": "{{instance}} {{volume}} total (TiB)"
    },
    {
     "expr": "sum by (instance, volume) (windows_logical_disk_free_bytes) / 1024 / 1024 / 1024 / 1024",
     "legendFormat": "{{instance}} {{volume}} free (TiB)"
    }
   ]
  },
  {
   "title": "Used Disk Space",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "sum by (instance, volume) ((windows_logical_disk_size_bytes - windows_logical_disk_free_bytes)) / 1024 / 1024 / 1024 / 1024",
     "legendFormat": "{{instance}} {{volume}} used (TiB)"
    }
   ]
  }
 ]
}